authapp/urls.py
import authapp.views as authapp
from django.urls import path

app_name = 'authapp'

urlpatterns = [
    path('login/ru', authapp.login, name='login'),
    path('logout/ru', authapp.logout, name='logout'),
    path('register/ru', authapp.register, name='register'),
    path('edit/ru', authapp.edit, name='edit'),
    path('login/', authapp.login_eng, name='login_eng'),
    path('logout/', authapp.logout_eng, name='logout_eng'),
    path('register/', authapp.register_eng, name='register_eng'),
    path('edit/', authapp.edit_eng, name='edit_eng'),
]

karateworld/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp.views import SearchView, shotokan, shito, goju, wado, \
    show_all_view, show_competitions_view, show_sport_camps_view, show_sport_science_view, show_editor_view, \
    show_nonfiction_view, show_photo_view, show_video_view

from mainapp_english.views import SearchViewEng, shotokan_eng, shito_eng, goju_eng, wado_eng, \
    show_all_view_eng, show_competitions_view_eng, show_sport_camps_view_eng, show_sport_science_view_eng, \
    show_editor_view_eng, show_photo_view_eng, show_video_view_eng

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('search/', SearchViewEng.as_view(), name = 'search_eng'),
    path('shotokan/', shotokan_eng, name='shotokan_eng'),
    path('shito-ryu/', shito_eng, name='shito_eng'),
    path('goju-ryu/', goju_eng, name='goju_eng'),
    path('wado-ryu/', wado_eng, name='wado_eng'),
    path('all_articles/', show_all_view_eng, name='show_all_eng'),
    path('competitions/', show_competitions_view_eng, name='show_competitions_eng'),
    path('sport_camps/', show_sport_camps_view_eng, name='show_sport_camps_eng'),
    path('sport_science/', show_sport_science_view_eng, name='show_sport_science_eng'),
    path('editor_in_chief/', show_editor_view_eng, name='show_editor_eng'),
    path('photo_albums/', show_photo_view_eng, name='show_photo_eng'),
    path('videos/', show_video_view_eng, name='show_video_eng'),
    #path('editor_articles/', show_editor_view_eng, name='show_editors_eng'),

    path('ru/search/', SearchView.as_view(), name = 'search'),
    path('ru/shotokan/', shotokan, name='shotokan'),
    path('ru/shito-ryu/', shito, name='shito'),
    path('ru/goju-ryu/', goju, name='goju'),
    path('ru/wado-ryu/', wado, name='wado'),
    path('ru/all_articles/', show_all_view, name='show_all'),
    path('ru/competitions/', show_competitions_view, name='show_competitions'),
    path('ru/sport_camps/', show_sport_camps_view, name='show_sport_camps'),
    path('ru/sport_science/', show_sport_science_view, name='show_sport_science'),
    path('ru/editor_in_chief/', show_editor_view, name='show_editor'),
    path('ru/nonfiction/other/', show_nonfiction_view, name='show_nonfiction'),
    path('ru/photo_albums/', show_photo_view, name='show_photo'),
    path('ru/videos/', show_video_view, name='show_video'),
    #path('ru/editor_articles/', show_editor_view, name='show_editors'),
    path('ru/', include('mainapp.urls', namespace = 'articles')),
    path('', include('mainapp_english.urls', namespace = 'main')),

    path('auth/', include('authapp.urls', namespace = 'auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mainapp/urls.py
import mainapp.views as mainapp
from django.urls import path

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.articles, name='main'),
    path('photo/', mainapp.gallery_photo, name='photo'),
    path('video/', mainapp.gallery_video, name='video'),
    #path('editor_in_chief/', mainapp.editor_in_chief, name='editor_in_chief'),
    path('photo/<pk>/', mainapp.photo_album, name='photo_id'),
    path('video/<pk>/', mainapp.video_album, name='video_id'),
    path('editor_in_chief/<pk>/', mainapp.editor_article, name='editor_id'),
    path('nonfiction/<pk>/', mainapp.nonfiction_article, name='nonfiction'),
    path('<pk>/', mainapp.articles, name='type'),
    path('<pk>/country/<id>/', mainapp.articles, name='country'),
    path('article/<pk>/', mainapp.article, name='id'),
]

mainapp/views.py
#coding=utf-8
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models import ArticleCategory, Country, Article, PhotoAlbum, Video, EditorArticle, Nonfiction, MainPageArticle
from commentapp.forms import CommentForm
from commentapp.models import Comment
from django.db.models import Q
from django.views import View


def articles(request, pk=None, id=None):

    article_item_all = Article.objects.all().order_by('-id')
    number_of_articles = len(article_item_all)
    article_item = article_item_all[:101]
    types = ArticleCategory.objects.all()
    countries = []
    show_all = ''
    show_competitions = ''
    show_sport_camps = ''
    show_sport_science = ''
    show_editor = ''
    show_nonfiction = ''
    article_type = {}

    if pk:

        if pk == '0':
            article_type = {'type_rus': 'все', 'pk':0}
            article_item = Article.objects.all().order_by('-id')[:101]
            show_all = 'Показать остальные статьи'

        elif pk == '1':
            article_item = Article.objects.filter(type__id=pk).order_by('-date_start')[:101]
            article_type = get_object_or_404(ArticleCategory, pk=pk)
            countries = Country.objects.all().order_by('name_rus')
            show_competitions = 'Показать остальные соревнования'
            if id:
                article_item = Article.objects.filter(country__id=id).order_by('-date_start')[:31]
                return render(request, 'mainapp/main.html',
                              {'article_item': article_item, 'article_type': article_type, 'types': types,
                               'countries': countries})

        elif pk == '2':
            article_item = Article.objects.filter(type__id=pk).order_by('-date_start')[:51]
            article_type = get_object_or_404(ArticleCategory, pk=pk)
            show_sport_camps = 'Показать остальные лагеря'

        elif pk == '3':
            article_item = Article.objects.filter(type__id=pk).order_by('-id')[:31]
            article_type = get_object_or_404(ArticleCategory, pk=pk)
            show_sport_science = 'Показать остальные статьи'

        elif pk == '4':
            #article_item = Article.objects.filter(type__id=pk).order_by('-id')[:31]
            article_item = EditorArticle.objects.all().order_by('-id')[:31]
            article_type = get_object_or_404(ArticleCategory, pk=pk)
            show_editor = 'Показать остальные статьи'

        elif pk == 'nonfiction':
            article_item = Nonfiction.objects.all().order_by('-id')[:31]
            #article_type = get_object_or_404(ArticleCategory, pk=pk)
            show_nonfiction = 'Показать остальные статьи'

        return render(request, 'mainapp/main.html', {'number_of_articles': number_of_articles,
                                                     'article_item': article_item, 'article_type': article_type,
                                                        'types': types, 'countries': countries, 'show_all': show_all,
                                                        'show_competitions': show_competitions,
                                                        'show_sport_camps': show_sport_camps,
                                                        'show_sport_science': show_sport_science,
                                                        'show_editor': show_editor, 'show_nonfiction': show_nonfiction})

    show_all = 'Показать остальные статьи'

    if len(MainPageArticle.objects.all()) > 0:
        main_page_article = MainPageArticle.objects.all().order_by('-id')[0]
    else:
        main_page_article = ''

    return render(request, 'mainapp/main.html', {'number_of_articles': number_of_articles, 'article_item': article_item,
                                                 'types': types, 'show_all': show_all,
                                                 'main_page_article': main_page_article})


def show_all_view(request):
    art = Article.objects.all().order_by('-id')[101:]
    return render(request, 'mainapp/show_all.html', {'articles': art})


def show_competitions_view(request):
    art = Article.objects.filter(type__id=1).order_by('-date_start')[101:]
    return render(request, 'mainapp/show_competitions.html', {'articles': art})


def show_sport_camps_view(request):
    art = Article.objects.filter(type__id=2).order_by('-date_start')[51:]
    return render(request, 'mainapp/show_sport_camps.html', {'articles': art})


def show_sport_science_view(request):
    art = Article.objects.filter(type__id=3).order_by('-id')[31:]
    return render(request, 'mainapp/show_sport_science.html', {'articles': art})


def show_editor_view(request):
    art = Article.objects.filter(type__id=4).order_by('-id')[31:]
    return render(request, 'mainapp/show_editor.html', {'articles': art})


def show_nonfiction_view(request):
    art = Nonfiction.objects.all().order_by('-id')[31:]
    return render(request, 'mainapp/show_nonfiction.html', {'articles': art})


def show_photo_view(request):
    photo = PhotoAlbum.objects.all().order_by('-id')[31:]
    return render(request, 'mainapp/show_photo.html', {'photo': photo})


def show_video_view(request):
    video = Video.objects.all().order_by('-id')[31:]
    return render(request, 'mainapp/show_video.html', {'video': video})


# def show_editor_view(request):
#     editors = EditorArticle.objects.all().order_by('-id')[31:]
#     return render(request, 'mainapp/show_editors.html', {'editors': editors})


def shotokan(request):
    return render(request, 'mainapp/styles/shotokan.html')


def shito(request):
    return render(request, 'mainapp/styles/shito.html')


def goju(request):
    return render(request, 'mainapp/styles/goju.html')


def wado(request):
    return render(request, 'mainapp/styles/wado.html')


def gallery_photo(request):

    number_of_albums = len(PhotoAlbum.objects.all().order_by('-id'))
    gallery_item = PhotoAlbum.objects.all().order_by('-id')[:31]

    return render(request, 'mainapp/photo.html', {'number_of_albums': number_of_albums, 'gallery_item': gallery_item})


def gallery_video(request):

    number_of_videos = len(Video.objects.all().order_by('-id'))
    video_item = Video.objects.all().order_by('-id')[:31]

    return render(request, 'mainapp/video.html', {'number_of_videos':number_of_videos, 'video_item': video_item})


# def editor_in_chief(request):
#
#     number_of_editors = len(EditorArticle.objects.all().order_by('-id'))
#     editor_item = EditorArticle.objects.all().order_by('-id')[:31]
#
#     return render(request, 'mainapp/editor_in_chief.html', {'number_of_editors': number_of_editors,
#                                                             'editor_item': editor_item})


class SearchView(View):

    template_name = 'mainapp/search.html'

    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('q')
        found_articles = Article.objects.filter(Q(title__icontains=query)|Q(text__icontains=query)|
                                                Q(title__icontains=query.title())|
                                                Q(text__icontains=query.title())|Q(city_description__icontains=query)|
                                                 Q(city_description__icontains=query.title())).order_by('-id')
        found_albums = PhotoAlbum.objects.filter(Q(title_rus__icontains=query)|
                                                 Q(title_rus__icontains=query.title())).order_by('-id')
        found_videos = Video.objects.filter(Q(title_rus__icontains=query) |
                                                 Q(title_rus__icontains=query.title())|Q(description_rus__icontains=query)|
                                                 Q(description_rus__icontains=query.title())).order_by('-id')
        found_editors = EditorArticle.objects.filter(Q(title__icontains=query) |
                                            Q(title__icontains=query.title())|Q(text__icontains=query) |
                                            Q(text__icontains=query.title())).order_by('-id')
        found_nonfiction = Nonfiction.objects.filter(Q(title__icontains=query) |
                                                     Q(title__icontains=query.title()) | Q(text__icontains=query) |
                                                     Q(text__icontains=query.title())).order_by('-id')

        context = {'found_articles': found_articles, 'found_albums': found_albums,
                   'found_videos': found_videos, 'found_editors': found_editors, 'found_nonfiction': found_nonfiction}

        return render(self.request, self.template_name, context)

#def search(request):
#
#    query = request.GET.get('q')
#    found_articles = Article.objects.filter(Q(title__icontains=query)|Q(text__icontains=query))
#
#    context = {'found_articles': found_articles}
#
#    return render(request, 'mainapp/search.html', context)

# -------------------------article_i-----------------------------


def article(request, pk=None):

    art = get_object_or_404(Article, pk=pk)
    comment = Comment.objects.filter(article_id=art).order_by('id')

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            comm = comment_form.save(commit=False)
            comm.author_id = request.user
            comm.article_id = art
            if request.user.avatar:
                comm.avatar = request.user.avatar.url
            comm.save()
            return HttpResponseRedirect('')

    else:
        comment_form = CommentForm()

    return render(request, 'mainapp/articles/article_{}.html'.format(pk), {'article': art, 'comment_form': comment_form,

mainapp/templates/mainapp/basic_templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style_auth_comm.css' %}">
    <link rel="icon" href="{% static 'images/index_1.jpg' %}"> {% block title %} {% endblock %} 
    <link href="https://fonts.googleapis.com/css?family=El+Messiri:400,700&amp;subset=cyrillic" rel="stylesheet">
    
    <link href="https://fonts.googleapis.com/css?family=EB+Garamond|Pattaya|Vollkorn|Kurale" rel="stylesheet">
    
    <link href="https://fonts.googleapis.com/css?family=Bree+Serif|Merriweather" rel="stylesheet">
    </head>

<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg_dark" style="font: bold small-caps 17px El Messiri;">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item {% if request.resolver_match.url_name == 'main' or request.resolver_match.url_name == 'type' or request.resolver_match.url_name == 'id' or request.resolver_match.url_name == 'country' or request.resolver_match.url_name == 'show_all' or request.resolver_match.url_name == 'show_competitions' or request.resolver_match.url_name == 'show_sport_camps' or request.resolver_match.url_name == 'show_sport_science' or request.resolver_match.url_name == 'editor_id' or request.resolver_match.url_name == 'show_editor' or request.resolver_match.url_name == 'nonfiction' or request.resolver_match.url_name == 'show_nonfiction' %}active{% endif %}"> <a class="nav-link" href="{% url 'articles:main' %}">Главная <span class="sr-only">(current)</span></a> </li>
                    <li class="nav-item dropdown {% if request.resolver_match.url_name == 'shotokan' or request.resolver_match.url_name == 'shito' or request.resolver_match.url_name == 'goju' or request.resolver_match.url_name == 'wado' %}active{% endif %}"> <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Стили</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown"> <a class="dropdown-item" href="{% url 'shotokan' %}">Сётокан</a> <a class="dropdown-item" href="{% url 'shito' %}">Сито Рю</a> <a class="dropdown-item" href="{% url 'goju' %}">Годжо Рю</a> <a class="dropdown-item" href="{% url 'wado' %}">Вадо Рю</a></div>
                    </li>
                    <li class="nav-item dropdown {% if request.resolver_match.url_name == 'photo' or request.resolver_match.url_name == 'photo_id' or request.resolver_match.url_name == 'video' or request.resolver_match.url_name == 'video_id' or request.resolver_match.url_name == 'show_photo' or request.resolver_match.url_name == 'show_video' %}active{% endif %}"> <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Галерея</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown"><a class="dropdown-item" href="{% url 'articles:photo' %}">Фото</a><a class="dropdown-item" href="{% url 'articles:video' %}">Видео</a></div>
                    </li>
                    <!-- <li class="nav-item {% if request.resolver_match.url_name == 'editor_in_chief' or request.resolver_match.url_name == 'editor_id' or request.resolver_match.url_name == 'show_editors' %}active{% endif %}"> <a class="nav-link" href="">Главный редактор</a> </li> -->
                    <li class="nav-item"> <a class="nav-link" href="http://www.karateworld.ru/" target="_blank">Старая версия сайта</a> </li>
                </ul>
                <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}" method="GET">
                    <input class="form-control mr-sm-2" type="search" placeholder="Поиск по сайту" aria-label="Search" name="q">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Найти</button>
                </form>
            </div>
        </nav>
        
        <div class="jumbotron jumbotron-fluid">
            <div class="container row">
                
                <div class='jumbotron jumbotron-fluid col-4 col-sm-2 offset-sm-2 col-md-2 offset-md-2 col-lg-2 offset-lg-2 col-xl-2 offset-xl-2'>
                    <div class="under_menu_logo">
                        <img src="{% static 'images/logo_head.jpg' %}">
                    </div>
                </div>
                
                <div class='jumbotron jumbotron-fluid col-4 col-sm-4 col-md-4 col-lg-4 col-xl-4'>
                    <div class="website_title">МИР КАРАТЭ</div>
                    <div class="under_menu_flags">
                        <a href="{% url 'main:main' %}"><img src="{% static 'images/eng.png' %}"></a>
                        <a href="{% url 'articles:main' %}"><img src="{% static 'images/rus.jpg' %}"></a>
                    </div>
                </div>                    
                
                <div class='jumbotron jumbotron-fluid col-4 col-sm-2 col-md-2 col-lg-2 col-xl-2'>
                    
                    <div class="under_menu_auth">
                        {% if user.is_authenticated %}
                            <a href="{% url 'auth:logout' %}">
                                <div class="login">Выйти</div>
                            </a>
                        {% else %}
                            <a href="{% url 'auth:login' %}">
                                <div class="login">Войти</div>
                            </a>
                        {% endif %}
                        
                        {% if user.is_authenticated %}
                        <div class="username"> <a href="{% url 'auth:edit' %}">{{ user.username|default:'Пользователь' }}</a> </div> {% endif %}
                        
                    </div>
                        
                </div>
                
            </div>
                <hr class="my-1">
        </div>        
        
        <div class="content"> {% block content%} {% endblock %} </div>
        
        <div class="footer">
   
        <footer>
            
            <div class="social">

                <div class="social_item">
                   <a href="https://www.instagram.com/karateworld.info/" target="_blank"><img src="/static/images/insta_icon.png"/></a>
                </div>

                <div class="social_item">
                   <a href="https://www.youtube.com/channel/UCewnNXzDEiimyOAbJfAOJWA" target="_blank"><img src="/static/images/youtube_icon.png"/></a>
                </div>

            </div>
            
            <a href="mailto:karateworld@karateworld.ru">karateworld@karateworld.ru</a>
            
            <div style="margin-top: 20px;">
                <!--LiveInternet counter--><script type="text/javascript">
                document.write("<a href='//www.liveinternet.ru/click' "+
                "target=_blank><img src='//counter.yadro.ru/hit?t13.4;r"+
                escape(document.referrer)+((typeof(screen)=="undefined")?"":
                ";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
                screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
                ";h"+escape(document.title.substring(0,150))+";"+Math.random()+
                "' alt='' title='LiveInternet: показано число просмотров за 24"+
                " часа, посетителей за 24 часа и за сегодня' "+
                "border='0' width='88' height='31'><\/a>")
                </script><!--/LiveInternet-->
            </div>

            <p style="font-size: 7pt; margin-top: 20px; padding-bottom: 20px;">developed by IgSvadkovsky</p>

        </footer>
    
    </div>
        
    </div>
    
    <!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    
    <script>
        $(document).ready(function () {
            $('.slideshow_button').click(function () {
                $('#slideshow').css('display', 'block');
            });
            $('#slideshow .close').click(function () {
                $('#slideshow').css('display', 'none');
            });
        })
        
        /*jQuery(function($) {
	        $(window).scroll(function(){
	            if($(this).scrollTop()==62){
	                $('.navbar').addClass('fixed_hidden');
	            }
                else if ($(this).scrollTop()>63){
                    $('.navbar').addClass('fixed_visible');
	            }
	            else if ($(this).scrollTop()<62){
	                $('.navbar').removeClass('fixed_hidden');
                    $('.navbar').removeClass('fixed_visible');
	            }
	        });
	    });*/
    </script>
    
</body>

</html>