authapp/urls.py
import authapp.views as authapp
from django.urls import path

app_name = 'authapp'

urlpatterns = [
    path('login/ru', authapp.login, name='login'),
    path('logout/ru', authapp.logout, name='logout'),
    path('register/ru', authapp.register, name='register'),
    path('edit/ru', authapp.edit, name='edit'),
    path('login/', authapp.login_eng, name='login_eng'),
    path('logout/', authapp.logout_eng, name='logout_eng'),
    path('register/', authapp.register_eng, name='register_eng'),
    path('edit/', authapp.edit_eng, name='edit_eng'),
]

karateworld/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp.views import SearchView, shotokan, shito, goju, wado, \
    show_all_view, show_competitions_view, show_sport_camps_view, show_sport_science_view, show_editor_view, \
    show_nonfiction_view, show_photo_view, show_video_view

from mainapp_english.views import SearchViewEng, shotokan_eng, shito_eng, goju_eng, wado_eng, \
    show_all_view_eng, show_competitions_view_eng, show_sport_camps_view_eng, show_sport_science_view_eng, \
    show_editor_view_eng, show_photo_view_eng, show_video_view_eng

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('search/', SearchViewEng.as_view(), name = 'search_eng'),
    path('shotokan/', shotokan_eng, name='shotokan_eng'),
    path('shito-ryu/', shito_eng, name='shito_eng'),
    path('goju-ryu/', goju_eng, name='goju_eng'),
    path('wado-ryu/', wado_eng, name='wado_eng'),
    path('all_articles/', show_all_view_eng, name='show_all_eng'),
    path('competitions/', show_competitions_view_eng, name='show_competitions_eng'),
    path('sport_camps/', show_sport_camps_view_eng, name='show_sport_camps_eng'),
    path('sport_science/', show_sport_science_view_eng, name='show_sport_science_eng'),
    path('editor_in_chief/', show_editor_view_eng, name='show_editor_eng'),
    path('photo_albums/', show_photo_view_eng, name='show_photo_eng'),
    path('videos/', show_video_view_eng, name='show_video_eng'),
    #path('editor_articles/', show_editor_view_eng, name='show_editors_eng'),

    path('ru/search/', SearchView.as_view(), name = 'search'),
    path('ru/shotokan/', shotokan, name='shotokan'),
    path('ru/shito-ryu/', shito, name='shito'),
    path('ru/goju-ryu/', goju, name='goju'),
    path('ru/wado-ryu/', wado, name='wado'),
    path('ru/all_articles/', show_all_view, name='show_all'),
    path('ru/competitions/', show_competitions_view, name='show_competitions'),
    path('ru/sport_camps/', show_sport_camps_view, name='show_sport_camps'),
    path('ru/sport_science/', show_sport_science_view, name='show_sport_science'),
    path('ru/editor_in_chief/', show_editor_view, name='show_editor'),
    path('ru/nonfiction/other/', show_nonfiction_view, name='show_nonfiction'),
    path('ru/photo_albums/', show_photo_view, name='show_photo'),
    path('ru/videos/', show_video_view, name='show_video'),
    #path('ru/editor_articles/', show_editor_view, name='show_editors'),
    path('ru/', include('mainapp.urls', namespace = 'articles')),
    path('', include('mainapp_english.urls', namespace = 'main')),

    path('auth/', include('authapp.urls', namespace = 'auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mainapp_english/urls.py
import mainapp_english.views as mainapp_english
from django.urls import path

app_name = 'mainapp_english'

urlpatterns = [
    path('', mainapp_english.articles_eng, name='main'),
    path('photo/', mainapp_english.gallery_photo_eng, name='photo'),
    path('video/', mainapp_english.gallery_video_eng, name='video'),
    #path('editor_in_chief/', mainapp_english.editor_in_chief_eng, name='editor_in_chief'),
    path('photo/<pk>/', mainapp_english.photo_album, name='photo_id'),
    path('video/<pk>/', mainapp_english.video_album, name='video_id'),
    path('editor_in_chief/<pk>/', mainapp_english.editor_article_eng, name='editor_id'),
    path('<pk>/', mainapp_english.articles_eng, name='type'),
    path('<pk>/country/<id>/', mainapp_english.articles_eng, name='country'),
    path('article/<pk>/', mainapp_english.article_eng, name='id'),
]

mainapp_english/views.py
#coding=utf-8
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models import EditorArticleEng, MainPageArticleEng  # , ArticleEng
from mainapp.models import Article, ArticleCategory, Country, PhotoAlbum, Video
from commentapp.forms import CommentForm
from commentapp.models import Comment
from django.db.models import Q
from django.views import View


def articles_eng(request, pk=None, id=None):

    article_item_all = Article.objects.all().order_by('-id')
    number_of_articles = len(article_item_all)
    article_item = article_item_all[:101]
    types = ArticleCategory.objects.all()
    countries = []
    show_all = ''
    show_competitions = ''
    show_sport_camps = ''
    show_sport_science = ''
    show_editor = ''
    article_type = {}

    if pk:

        if pk == '0':
            article_type = {'type_rus': 'все', 'pk':0}
            article_item = Article.objects.all().order_by('-id')[:101]
            show_all = 'Show the rest articles'

        elif pk == '1':
            article_item = Article.objects.filter(type__id=pk).order_by('-date_start')[:101]
            article_type = get_object_or_404(ArticleCategory, pk=pk)
            countries = Country.objects.all().order_by('name_eng')
            show_competitions = 'Show the rest competitions'
            if id:
                article_item = Article.objects.filter(country__id=id).order_by('-date_start')[:31]
                return render(request, 'mainapp_english/main_eng.html',
                              {'article_item': article_item, 'article_type': article_type, 'types': types,
                               'countries': countries})

        elif pk == '2':
            article_item = Article.objects.filter(type__id=pk).order_by('-date_start')[:51]
            article_type = get_object_or_404(ArticleCategory, pk=pk)
            show_sport_camps = 'Show the rest camps'

        elif pk == '3':
            article_item = Article.objects.filter(type__id=pk).order_by('-id')[:31]
            article_type = get_object_or_404(ArticleCategory, pk=pk)
            show_sport_science = 'Show the rest articles'

        elif pk == '4':
            #article_item = ArticleEng.objects.filter(type__id=pk).order_by('-id')[:31]
            article_item = EditorArticleEng.objects.all().order_by('-id')[:31]
            article_type = get_object_or_404(ArticleCategory, pk=pk)
            show_editor = 'Show the rest articles'

        return render(request, 'mainapp_english/main_eng.html', {'number_of_articles': number_of_articles,
                                                     'article_item': article_item, 'article_type': article_type,
                                                        'types': types, 'countries': countries, 'show_all': show_all,
                                                        'show_competitions': show_competitions,
                                                        'show_sport_camps': show_sport_camps,
                                                        'show_sport_science': show_sport_science,
                                                        'show_editor': show_editor})

    show_all = 'Show the rest articles'

    if len(MainPageArticleEng.objects.all()) > 0:
        main_page_article = MainPageArticleEng.objects.all().order_by('-id')[0]
    else:
        main_page_article = ''

    return render(request, 'mainapp_english/main_eng.html', {'number_of_articles': number_of_articles, 'article_item': article_item,
                                                 'types': types, 'show_all': show_all,
                                                             'main_page_article': main_page_article})


def show_all_view_eng(request):
    art = Article.objects.all().order_by('-id')[101:]
    return render(request, 'mainapp_english/show_all_eng.html', {'articles': art})


def show_competitions_view_eng(request):
    art = Article.objects.filter(type__id=1).order_by('-date_start')[101:]
    return render(request, 'mainapp_english/show_competitions_eng.html', {'articles': art})


def show_sport_camps_view_eng(request):
    art = Article.objects.filter(type__id=2).order_by('-date_start')[51:]
    return render(request, 'mainapp_english/show_sport_camps_eng.html', {'articles': art})


def show_sport_science_view_eng(request):
    art = Article.objects.filter(type__id=3).order_by('-id')[31:]
    return render(request, 'mainapp_english/show_sport_science_eng.html', {'articles': art})


def show_editor_view_eng(request):
    art = Article.objects.filter(type__id=4).order_by('-id')[31:]
    return render(request, 'mainapp_english/show_editor_eng.html', {'articles': art})


def show_photo_view_eng(request):
    photo = PhotoAlbum.objects.all().order_by('-id')[31:]
    return render(request, 'mainapp_english/show_photo_eng.html', {'photo': photo})


def show_video_view_eng(request):
    video = Video.objects.all().order_by('-id')[31:]
    return render(request, 'mainapp_english/show_video_eng.html', {'video': video})


# def show_editor_view_eng(request):
#     editors = EditorArticleEng.objects.all().order_by('-id')[31:]
#     return render(request, 'mainapp_english/show_editors_eng.html', {'editors': editors})


def shotokan_eng(request):
    return render(request, 'mainapp_english/styles/shotokan_eng.html')


def shito_eng(request):
    return render(request, 'mainapp_english/styles/shito_eng.html')


def goju_eng(request):
    return render(request, 'mainapp_english/styles/goju_eng.html')


def wado_eng(request):
    return render(request, 'mainapp_english/styles/wado_eng.html')


def gallery_photo_eng(request):

    number_of_albums = len(PhotoAlbum.objects.all().order_by('-id'))
    gallery_item = PhotoAlbum.objects.all().order_by('-id')[:31]

    return render(request, 'mainapp_english/photo_eng.html', {'number_of_albums': number_of_albums, 'gallery_item': gallery_item})


def gallery_video_eng(request):

    number_of_videos = len(Video.objects.all().order_by('-id'))
    video_item = Video.objects.all().order_by('-id')[:31]

    return render(request, 'mainapp_english/video_eng.html', {'number_of_videos':number_of_videos, 'video_item': video_item})


# def editor_in_chief_eng(request):
#
#     number_of_editors = len(EditorArticleEng.objects.all().order_by('-id'))
#     editor_item = EditorArticleEng.objects.all().order_by('-id')[:31]
#
#     return render(request, 'mainapp_english/editor_in_chief_eng.html', {'number_of_editors': number_of_editors,
#                                                             'editor_item': editor_item})


class SearchViewEng(View):

    template_name = 'mainapp_english/search_eng.html'

    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('q')
        found_articles = Article.objects.filter(Q(title_eng__icontains=query)|Q(text_eng__icontains=query)|
                                                Q(title_eng__icontains=query.title())|
                                                Q(text_eng__icontains=query.title())|Q(city_description_eng__icontains=query)|
                                                 Q(city_description_eng__icontains=query.title())).order_by('-id')
        found_albums = PhotoAlbum.objects.filter(Q(title_eng__icontains=query)|
                                                 Q(title_eng__icontains=query.title())).order_by('-id')
        found_videos = Video.objects.filter(Q(title_eng__icontains=query) |
                                                 Q(title_eng__icontains=query.title())|Q(description_eng__icontains=query)|
                                                 Q(description_eng__icontains=query.title())).order_by('-id')
        found_editors = EditorArticleEng.objects.filter(Q(title__icontains=query) |
                                            Q(title__icontains=query.title())|Q(text__icontains=query) |
                                            Q(text__icontains=query.title())).order_by('-id')

        context = {'found_articles': found_articles, 'found_albums': found_albums,
                   'found_videos': found_videos, 'found_editors': found_editors}

        return render(self.request, self.template_name, context)

#-------------------------article_i_eng-----------------------------


def article_eng(request, pk=None):

    art = get_object_or_404(Article, pk=pk)
    comment = Comment.objects.filter(article_id=art).order_by('id')

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            comm = comment_form.save(commit=False)
            comm.author_id = request.user
            comm.article_id = art
            if request.user.avatar:
                comm.avatar = request.user.avatar.url
            comm.save()
            return HttpResponseRedirect('')

    else:
        comment_form = CommentForm()

    return render(request, 'mainapp_english/articles/article_{}_eng.html'.format(pk),
                  {'article': art, 'comment_form': comment_form, 'comment': comment})


#-------------------------photo_i-----------------------------


def photo_album(request, pk=None):

    photo = get_object_or_404(PhotoAlbum, pk=pk)
    comment = Comment.objects.filter(photo_album_id=photo).order_by('id')

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            comm = comment_form.save(commit=False)
            comm.author_id = request.user
            comm.photo_album_id = photo
            if request.user.avatar:
                comm.avatar = request.user.avatar.url
            comm.save()
            return HttpResponseRedirect('')

    else:
        comment_form = CommentForm()


mainapp_english/templates/mainapp_english/main_eng.html
{% extends 'mainapp_english/basic_templates/base_eng.html'%}
{% load staticfiles %}

{% block title %}
   <title>Karate World</title>
{% endblock %}

{% block content %}

    <div class="menu_articles">

        {% for type in types %}
            <a href="{% url 'main:type' type.pk %}">
                <div class="item_menu_articles" {% if type.type_eng == 'Sport camps' %} style="display: none" {% endif %}>
                    {{ type.type_eng }}
                </div> 
            </a>
        {% endfor %}

        <!-- <a href="{% url 'main:type' 0 %}">
            <div class="item_menu_articles">
                All articles
            </div> 
        </a> -->

    </div>
    
    {% if countries %}
        <!--<div class="select_country">-->
            <div class="dropdown">
                <a class="select_country dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Choose country
                </a>
                
                <!--a class="btn btn-secondary dropdown-toggle"-->

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    {% for country in countries %}
                        <a class="dropdown-item" href="{% url 'main:country' 1 country.id %}">
                            {{ country.name_eng }}
                        </a>
                    {% endfor %}
                </div>
            </div>
        <!--</div>-->
    {% endif %}

    <div class="menu_countries">

        {% for country in countries %}
            <a href="{% url 'main:country' 1 country.id %}">
                <div class="item_menu_countries">
                    {{ country.name_eng }}
                </div>
            </a>
        {% endfor %}

    </div>
    
    <div class="container_articles">
        
        {% if main_page_article %}
       
            <a {% if main_page_article.editor %} href="{{main_page_article.editor.get_absolute_url}}" {% elif main_page_article.album %} href="{{main_page_article.album.get_absolute_url_eng}}" {% elif main_page_article.video %} href="{{main_page_article.video.get_absolute_url_eng}}" {%endif%} target="_blank" style="text-decoration: none">

                <div class="item_articles">

                    <img {% if main_page_article.editor %} src="{% static 'images/plume.jpg' %}" {% elif main_page_article.album %} src="{{main_page_article.album.image1.url}}" {% elif main_page_article.video %} src="{% static 'images/video.jpg' %}" {%endif%}>

                    <div class="item_articles_title">
                        <div class="item_articles_title_inner"> {% if main_page_article.editor %} {{main_page_article.editor.title}} {% elif main_page_article.album %} {{main_page_article.album.title_eng}} {% elif main_page_article.video %} {{main_page_article.video.title_eng}} {%endif%} </div>
                    </div>

                </div>

            </a>
                
        {% endif %}


        {% for item in article_item %}

            <a {% if not show_editor %} href="{% url 'main:id' item.pk %}" {% else %} href="{% url 'main:editor_id' item.pk %}" {% endif %} target="_blank" style="text-decoration: none">

                    <div class="item_articles">

                        {% if item.image %}
                            <img src="{{ item.image.url }}">
                        {% elif show_editor %}
                            <img src="{% static 'images/plume.jpg' %}">
                        {% else %}
                            <img src="{{ item.country.flag.url }}">
                        {% endif %}

                        <!--{% if item.flag %}<img src="{{ item.flag.url }}">{% endif %}-->

                        <div class="item_articles_title">
                            <div class="item_articles_title_inner">{% if not show_editor %} {{ item.title_eng }} {% else %} {{ item.title }} {% endif %}</div>
                        </div>

                    </div>
                    
            </a>

        {% endfor %}        

    </div>
    
    {% if number_of_articles > 100 %}
    
        <div style="text-align: center; margin-top: 10px;">
    
            {% if show_all %}
                <a href="{% url 'show_all_eng'%}" target="_blank"><button type="button" class="btn btn-light">{{show_all}}</button></a>
            {% endif %}

            {% if show_competitions %}
                <a href="{% url 'show_competitions_eng'%}" target="_blank"><button type="button" class="btn btn-light">{{show_competitions}}</button></a>
            {% endif %}

            {% if show_sport_camps %}
                <a href="{% url 'show_sport_camps_eng'%}" target="_blank"><button type="button" class="btn btn-light">{{show_sport_camps}}</button></a>
            {% endif %}

            {% if show_sport_science %}
                <a href="{% url 'show_sport_science_eng'%}" target="_blank"><button type="button" class="btn btn-light">{{show_sport_science}}</button></a>
            {% endif %}

            {% if show_editor %}
                <a href="{% url 'show_editor_eng'%}" target="_blank"><button type="button" class="btn btn-light">{{show_editor}}</button></a>
            {% endif %}
        
        </div>
    
    {% endif %}
    
{% endblock %}

mainapp_english/templates/mainapp_english/photo_eng.html
{% extends 'mainapp_english/basic_templates/base_gallery_eng.html'%}
{% load staticfiles %}

{% block title %}
   <title>Karate world: Photo albums</title>
{% endblock %}

{% block content %}
   
   
   
   <div class="title_article_i gallery_title" style="margin-bottom: 10px;">Photo albums</div>
    
        <div class="container card-columns">
            
            {% for item in gallery_item %}
               <a href="{% url 'main:photo_id' item.pk %}"><div class="card text-white">{%if item.image2%}<img class="card-img" src="{{item.image2.url}}" alt="image">{%endif%}
                <div class="card-img-overlay d-flex flex-column justify-content-between">
                    <div class="top_block text-right">
                        {{item.date}}
                    </div>
                    <div class="bottom_block">
                        {{item.title_eng}}
                    </div>
                </div>
                </div></a> 
            {% endfor %}

       </div>
       
    {% if number_of_albums > 30 %}
    
        <div style="text-align: center; margin-top: 10px;">
    
            <a href="{% url 'show_photo_eng'%}" target="_blank"><button type="button" class="btn btn-dark">Show the rest albums</button></a>
        
        </div>
    
    {% endif %}
    
{% endblock %}

mainapp_english/templates/mainapp_english/search_eng.html
{% extends 'mainapp_english/basic_templates/base_no_logo_eng.html'%}

{% load staticfiles %}

{% block title %}
   <title>Photo albums: Search results</title>
{% endblock %}
          
{% block content %}
    <div>  
    <h3>Search results: {{ found_articles.count|add:found_editors.count|add:found_albums.count|add:found_videos.count }}</h3>
    
    {% if found_articles %}<h5 align="center" style="margin-top: 10px; color: #b3051c;">Main page articles</h5>{% endif %}
    
    <div class="search_container">
        {% for article in found_articles %}
            <a class="search_title_text" href="{{ article.get_absolute_url_eng }}" target="_blank">

                <div class="search_date">
                    {{ article.date }}
                </div>
                <div class="search_title">
                    {{ article.title_eng }}
                </div>

            </a>
        {% endfor %}
    </div>
    
    {% if found_editors %}<h5 align="center" style="margin-top: 10px; color: #b3051c;">Editor in chief's articles</h5>{% endif %}
    
    <div class="search_container">
        {% for editor in found_editors %}
            <a class="search_title_text" href="{{ editor.get_absolute_url }}" target="_blank">

                <div class="search_date">
                    {{ editor.date }}
                </div>
                <div class="search_title">
                    {{ editor.title }}
                </div>

            </a>
        {% endfor %}
    </div>
    
    {% if found_albums %}<h5 align="center" style="margin-top: 10px; color: #b3051c;">Photo albums</h5>{% endif %}
    
    <div class="search_container">
        {% for album in found_albums %}
            <a class="search_title_text" href="{{ album.get_absolute_url_eng }}" target="_blank">

                <div class="search_date">
                    {{ album.date }}
                </div>
                <div class="search_title">
                    {{ album.title_eng }}
                </div>

            </a>
        {% endfor %}
    </div>
    
    {% if found_videos %}<h5 align="center" style="margin-top: 10px; color: #b3051c;">Videos</h5>{% endif %}
    
    <div class="search_container">
        {% for video in found_videos %}
            <a class="search_title_text" href="{{ video.get_absolute_url_eng }}" target="_blank">

                <div class="search_date">
                    {{ video.date }}
                </div>
                <div class="search_title">
                    {{ video.title_eng }}
                </div>

            </a>
        {% endfor %}
    </div>
    
    </div>

{% endblock %}

mainapp_english/templates/mainapp_english/show_all_eng.html
{% extends 'mainapp_english/basic_templates/base_no_logo_eng.html'%}

{% load staticfiles %}

{% block title %}
   <title>Karate world: All articles</title>
{% endblock %}
          
{% block content %}
   
    <div>
         
        <h3>All articles: {{articles.count}}</h3>

        <div class="search_container">
            {% for article in articles %}
                <a class="search_title_text" href="{{ article.get_absolute_url }}" target="_blank">

                    <div class="search_date">
                        {{ article.date }}
                    </div>
                    <div class="search_title">
                        {{ article.title }}
                    </div>
                    
                </a>
            {% endfor %}
        </div>
    
    </div>

{% endblock %}

mainapp_english/templates/mainapp_english/show_competitions_eng.html
{% extends 'mainapp_english/basic_templates/base_no_logo_eng.html'%}

{% load staticfiles %}

{% block title %}
   <title>Karate world: Competitions</title>
{% endblock %}
          
{% block content %}
    <div> 
        
        <h3>Competitions: {{articles.count}}</h3>

        <div class="search_container">
            {% for article in articles %}
                <a class="search_title_text" href="{{ article.get_absolute_url }}" target="_blank">

                    <div class="search_date">
                        {{ article.date }}
                    </div>
                    <div class="search_title">
                        {{ article.title }}
                    </div>

                </a>
            {% endfor %}
        </div>
    
    </div>

{% endblock %}

mainapp_english/templates/mainapp_english/show_editor_eng.html
{% extends 'mainapp_english/basic_templates/base_no_logo_eng.html'%}

{% load staticfiles %}

{% block title %}
   <title>Karate world: Editor in chief's articles</title>
{% endblock %}
          
{% block content %}
   
    <div>
         
        <h3>Editor in chief's articles: {{articles.count}}</h3>

        <div class="search_container">
            {% for article in articles %}
                <a class="search_title_text" href="{{ article.get_absolute_url }}" target="_blank">

                    <div class="search_date">
                        {{ article.date }}
                    </div>
                    <div class="search_title">
                        {{ article.title }}
                    </div>
                    
                </a>
            {% endfor %}
        </div>
    
    </div>

{% endblock %}

mainapp_english/templates/mainapp_english/show_photo_eng.html
{% extends 'mainapp_english/basic_templates/base_no_logo_eng.html'%}

{% load staticfiles %}

{% block title %}
   <title>Karate world: Photo albums</title>
{% endblock %}
          
{% block content %}
   
    <div>
         
        <h3>Photo albums: {{photo.count}}</h3>

        <div class="search_container">
            {% for photo in photo %}
                <a class="search_title_text" href="{{ photo.get_absolute_url_eng }}" target="_blank">

                    <div class="search_date">
                        {{ photo.date }}
                    </div>
                    <div class="search_title">
                        {{ photo.title_eng }}
                    </div>
                    
                </a>
            {% endfor %}
        </div>
    
    </div>

{% endblock %}

mainapp_english/templates/mainapp_english/show_sport_camps_eng.html
{% extends 'mainapp_english/basic_templates/base_no_logo_eng.html'%}

{% load staticfiles %}

{% block title %}
   <title>Karate world: Sport camps</title>
{% endblock %}
          
{% block content %}
   
    <div>
         
        <h3>Sport camps: {{articles.count}}</h3>

        <div class="search_container">
            {% for article in articles %}
                <a class="search_title_text" href="{{ article.get_absolute_url }}" target="_blank">

                    <div class="search_date">
                        {{ article.date }}
                    </div>
                    <div class="search_title">
                        {{ article.title }}
                    </div>
                    
                </a>
            {% endfor %}
        </div>
    
    </div>

{% endblock %}

mainapp_english/templates/mainapp_english/show_sport_science_eng.html
{% extends 'mainapp_english/basic_templates/base_no_logo_eng.html'%}

{% load staticfiles %}

{% block title %}
   <title>Karate world: Sport science</title>
{% endblock %}
          
{% block content %}
   
    <div>
         
        <h3>Sport science: {{articles.count}}</h3>

        <div class="search_container">
            {% for article in articles %}
                <a class="search_title_text" href="{{ article.get_absolute_url }}" target="_blank">

                    <div class="search_date">
                        {{ article.date }}
                    </div>
                    <div class="search_title">
                        {{ article.title }}
                    </div>
                    
                </a>
            {% endfor %}
        </div>
    
    </div>

{% endblock %}

mainapp_english/templates/mainapp_english/show_video_eng.html
{% extends 'mainapp_english/basic_templates/base_no_logo_eng.html'%}

{% load staticfiles %}

{% block title %}
   <title>Karate world: Videos</title>
{% endblock %}
          
{% block content %}
   
    <div>
         
        <h3>Videos: {{video.count}}</h3>

        <div class="search_container">
            {% for video in video %}
                <a class="search_title_text" href="{{ video.get_absolute_url_eng }}" target="_blank">

                    <div class="search_date">
                        {{ video.date }}
                    </div>
                    <div class="search_title">
                        {{ video.title_eng }}
                    </div>
                    
                </a>
            {% endfor %}
        </div>
    
    </div>

{% endblock %}

mainapp_english/templates/mainapp_english/video_eng.html
{% extends 'mainapp_english/basic_templates/base_gallery_eng.html'%}
{% load staticfiles %}

{% block title %}
   <title>Karate world: Videos</title>
{% endblock %}

{% block content %}
   
   
   
    <div class="title_article_i gallery_title" style="margin-bottom: 10px;">Videos</div>
    
    <div class="container d-flex flex-row justify-content-center flex-wrap">
        
        {% for item in video_item %}
        
            <a href="{% url 'main:video_id' item.pk%}" class="video_item_link"><div class="card text-white mb-3 video_item" style="max-width: 18rem;">
                <div class="card-body">
                <h5 class="card-title text-center">{{item.title_eng}}</h5>
                </div>
            </div></a>
            
        {% endfor %}
    
    </div>
    
    {% if number_of_videos > 30 %}
    
        <div style="text-align: center; margin-top: 10px;">
    
            <a href="{% url 'show_video_eng'%}" target="_blank"><button type="button" class="btn btn-dark">Show the rest videos</button></a>
        
        </div>
    
    {% endif %}
    
{% endblock %}