authapp/urls.py
import authapp.views as authapp
from django.urls import path

app_name = 'authapp'

urlpatterns = [
    path('login/ru', authapp.login, name='login'),
    path('logout/ru', authapp.logout, name='logout'),
    path('register/ru', authapp.register, name='register'),
    path('edit/ru', authapp.edit, name='edit'),
    path('login/', authapp.login_eng, name='login_eng'),
    path('logout/', authapp.logout_eng, name='logout_eng'),
    path('register/', authapp.register_eng, name='register_eng'),
    path('edit/', authapp.edit_eng, name='edit_eng'),
]

karateworld/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp.views import SearchView, shotokan, shito, goju, wado, \
    show_all_view, show_competitions_view, show_sport_camps_view, show_sport_science_view, show_editor_view, \
    show_nonfiction_view, show_photo_view, show_video_view

from mainapp_english.views import SearchViewEng, shotokan_eng, shito_eng, goju_eng, wado_eng, \
    show_all_view_eng, show_competitions_view_eng, show_sport_camps_view_eng, show_sport_science_view_eng, \
    show_editor_view_eng, show_photo_view_eng, show_video_view_eng

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('search/', SearchViewEng.as_view(), name = 'search_eng'),
    path('shotokan/', shotokan_eng, name='shotokan_eng'),
    path('shito-ryu/', shito_eng, name='shito_eng'),
    path('goju-ryu/', goju_eng, name='goju_eng'),
    path('wado-ryu/', wado_eng, name='wado_eng'),
    path('all_articles/', show_all_view_eng, name='show_all_eng'),
    path('competitions/', show_competitions_view_eng, name='show_competitions_eng'),
    path('sport_camps/', show_sport_camps_view_eng, name='show_sport_camps_eng'),
    path('sport_science/', show_sport_science_view_eng, name='show_sport_science_eng'),
    path('editor_in_chief/', show_editor_view_eng, name='show_editor_eng'),
    path('photo_albums/', show_photo_view_eng, name='show_photo_eng'),
    path('videos/', show_video_view_eng, name='show_video_eng'),
    #path('editor_articles/', show_editor_view_eng, name='show_editors_eng'),

    path('ru/search/', SearchView.as_view(), name = 'search'),
    path('ru/shotokan/', shotokan, name='shotokan'),
    path('ru/shito-ryu/', shito, name='shito'),
    path('ru/goju-ryu/', goju, name='goju'),
    path('ru/wado-ryu/', wado, name='wado'),
    path('ru/all_articles/', show_all_view, name='show_all'),
    path('ru/competitions/', show_competitions_view, name='show_competitions'),
    path('ru/sport_camps/', show_sport_camps_view, name='show_sport_camps'),
    path('ru/sport_science/', show_sport_science_view, name='show_sport_science'),
    path('ru/editor_in_chief/', show_editor_view, name='show_editor'),
    path('ru/nonfiction/other/', show_nonfiction_view, name='show_nonfiction'),
    path('ru/photo_albums/', show_photo_view, name='show_photo'),
    path('ru/videos/', show_video_view, name='show_video'),
    #path('ru/editor_articles/', show_editor_view, name='show_editors'),
    path('ru/', include('mainapp.urls', namespace = 'articles')),
    path('', include('mainapp_english.urls', namespace = 'main')),

    path('auth/', include('authapp.urls', namespace = 'auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mainapp/urls.py
import mainapp.views as mainapp
from django.urls import path

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.articles, name='main'),
    path('photo/', mainapp.gallery_photo, name='photo'),
    path('video/', mainapp.gallery_video, name='video'),
    #path('editor_in_chief/', mainapp.editor_in_chief, name='editor_in_chief'),
    path('photo/<pk>/', mainapp.photo_album, name='photo_id'),
    path('video/<pk>/', mainapp.video_album, name='video_id'),
    path('editor_in_chief/<pk>/', mainapp.editor_article, name='editor_id'),
    path('nonfiction/<pk>/', mainapp.nonfiction_article, name='nonfiction'),
    path('<pk>/', mainapp.articles, name='type'),
    path('<pk>/country/<id>/', mainapp.articles, name='country'),
    path('article/<pk>/', mainapp.article, name='id'),
]

mainapp/views.py
#coding=utf-8
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models import ArticleCategory, Country, Article, PhotoAlbum, Video, EditorArticle, Nonfiction, MainPageArticle
from commentapp.forms import CommentForm
from commentapp.models import Comment
from django.db.models import Q
from django.views import View


def articles(request, pk=None, id=None):

    article_item_all = Article.objects.all().order_by('-id')
    number_of_articles = len(article_item_all)
    article_item = article_item_all[:101]
    types = ArticleCategory.objects.all()
    countries = []
    show_all = ''
    show_competitions = ''
    show_sport_camps = ''
    show_sport_science = ''
    show_editor = ''
    show_nonfiction = ''
    article_type = {}

    if pk:

        if pk == '0':
            article_type = {'type_rus': 'все', 'pk':0}
            article_item = Article.objects.all().order_by('-id')[:101]
            show_all = 'Показать остальные статьи'

        elif pk == '1':
            article_item = Article.objects.filter(type__id=pk).order_by('-date_start')[:101]
            article_type = get_object_or_404(ArticleCategory, pk=pk)
            countries = Country.objects.all().order_by('name_rus')
            show_competitions = 'Показать остальные соревнования'
            if id:
                article_item = Article.objects.filter(country__id=id).order_by('-date_start')[:31]
                return render(request, 'mainapp/main.html',
                              {'article_item': article_item, 'article_type': article_type, 'types': types,
                               'countries': countries})

        elif pk == '2':
            article_item = Article.objects.filter(type__id=pk).order_by('-date_start')[:51]
            article_type = get_object_or_404(ArticleCategory, pk=pk)
            show_sport_camps = 'Показать остальные лагеря'

        elif pk == '3':
            article_item = Article.objects.filter(type__id=pk).order_by('-id')[:31]
            article_type = get_object_or_404(ArticleCategory, pk=pk)
            show_sport_science = 'Показать остальные статьи'

        elif pk == '4':
            #article_item = Article.objects.filter(type__id=pk).order_by('-id')[:31]
            article_item = EditorArticle.objects.all().order_by('-id')[:31]
            article_type = get_object_or_404(ArticleCategory, pk=pk)
            show_editor = 'Показать остальные статьи'

        elif pk == 'nonfiction':
            article_item = Nonfiction.objects.all().order_by('-id')[:31]
            #article_type = get_object_or_404(ArticleCategory, pk=pk)
            show_nonfiction = 'Показать остальные статьи'

        return render(request, 'mainapp/main.html', {'number_of_articles': number_of_articles,
                                                     'article_item': article_item, 'article_type': article_type,
                                                        'types': types, 'countries': countries, 'show_all': show_all,
                                                        'show_competitions': show_competitions,
                                                        'show_sport_camps': show_sport_camps,
                                                        'show_sport_science': show_sport_science,
                                                        'show_editor': show_editor, 'show_nonfiction': show_nonfiction})

    show_all = 'Показать остальные статьи'

    if len(MainPageArticle.objects.all()) > 0:
        main_page_article = MainPageArticle.objects.all().order_by('-id')[0]
    else:
        main_page_article = ''

    return render(request, 'mainapp/main.html', {'number_of_articles': number_of_articles, 'article_item': article_item,
                                                 'types': types, 'show_all': show_all,
                                                 'main_page_article': main_page_article})


def show_all_view(request):
    art = Article.objects.all().order_by('-id')[101:]
    return render(request, 'mainapp/show_all.html', {'articles': art})


def show_competitions_view(request):
    art = Article.objects.filter(type__id=1).order_by('-date_start')[101:]
    return render(request, 'mainapp/show_competitions.html', {'articles': art})


def show_sport_camps_view(request):
    art = Article.objects.filter(type__id=2).order_by('-date_start')[51:]
    return render(request, 'mainapp/show_sport_camps.html', {'articles': art})


def show_sport_science_view(request):
    art = Article.objects.filter(type__id=3).order_by('-id')[31:]
    return render(request, 'mainapp/show_sport_science.html', {'articles': art})


def show_editor_view(request):
    art = Article.objects.filter(type__id=4).order_by('-id')[31:]
    return render(request, 'mainapp/show_editor.html', {'articles': art})


def show_nonfiction_view(request):
    art = Nonfiction.objects.all().order_by('-id')[31:]
    return render(request, 'mainapp/show_nonfiction.html', {'articles': art})


def show_photo_view(request):
    photo = PhotoAlbum.objects.all().order_by('-id')[31:]
    return render(request, 'mainapp/show_photo.html', {'photo': photo})


def show_video_view(request):
    video = Video.objects.all().order_by('-id')[31:]
    return render(request, 'mainapp/show_video.html', {'video': video})


# def show_editor_view(request):
#     editors = EditorArticle.objects.all().order_by('-id')[31:]
#     return render(request, 'mainapp/show_editors.html', {'editors': editors})


def shotokan(request):
    return render(request, 'mainapp/styles/shotokan.html')


def shito(request):
    return render(request, 'mainapp/styles/shito.html')


def goju(request):
    return render(request, 'mainapp/styles/goju.html')


def wado(request):
    return render(request, 'mainapp/styles/wado.html')


def gallery_photo(request):

    number_of_albums = len(PhotoAlbum.objects.all().order_by('-id'))
    gallery_item = PhotoAlbum.objects.all().order_by('-id')[:31]

    return render(request, 'mainapp/photo.html', {'number_of_albums': number_of_albums, 'gallery_item': gallery_item})


def gallery_video(request):

    number_of_videos = len(Video.objects.all().order_by('-id'))
    video_item = Video.objects.all().order_by('-id')[:31]

    return render(request, 'mainapp/video.html', {'number_of_videos':number_of_videos, 'video_item': video_item})


# def editor_in_chief(request):
#
#     number_of_editors = len(EditorArticle.objects.all().order_by('-id'))
#     editor_item = EditorArticle.objects.all().order_by('-id')[:31]
#
#     return render(request, 'mainapp/editor_in_chief.html', {'number_of_editors': number_of_editors,
#                                                             'editor_item': editor_item})


class SearchView(View):

    template_name = 'mainapp/search.html'

    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('q')
        found_articles = Article.objects.filter(Q(title__icontains=query)|Q(text__icontains=query)|
                                                Q(title__icontains=query.title())|
                                                Q(text__icontains=query.title())|Q(city_description__icontains=query)|
                                                 Q(city_description__icontains=query.title())).order_by('-id')
        found_albums = PhotoAlbum.objects.filter(Q(title_rus__icontains=query)|
                                                 Q(title_rus__icontains=query.title())).order_by('-id')
        found_videos = Video.objects.filter(Q(title_rus__icontains=query) |
                                                 Q(title_rus__icontains=query.title())|Q(description_rus__icontains=query)|
                                                 Q(description_rus__icontains=query.title())).order_by('-id')
        found_editors = EditorArticle.objects.filter(Q(title__icontains=query) |
                                            Q(title__icontains=query.title())|Q(text__icontains=query) |
                                            Q(text__icontains=query.title())).order_by('-id')
        found_nonfiction = Nonfiction.objects.filter(Q(title__icontains=query) |
                                                     Q(title__icontains=query.title()) | Q(text__icontains=query) |
                                                     Q(text__icontains=query.title())).order_by('-id')

        context = {'found_articles': found_articles, 'found_albums': found_albums,
                   'found_videos': found_videos, 'found_editors': found_editors, 'found_nonfiction': found_nonfiction}

        return render(self.request, self.template_name, context)

#def search(request):
#
#    query = request.GET.get('q')
#    found_articles = Article.objects.filter(Q(title__icontains=query)|Q(text__icontains=query))
#
#    context = {'found_articles': found_articles}
#
#    return render(request, 'mainapp/search.html', context)

# -------------------------article_i-----------------------------


def article(request, pk=None):

    art = get_object_or_404(Article, pk=pk)
    comment = Comment.objects.filter(article_id=art).order_by('id')

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            comm = comment_form.save(commit=False)
            comm.author_id = request.user
            comm.article_id = art
            if request.user.avatar:
                comm.avatar = request.user.avatar.url
            comm.save()
            return HttpResponseRedirect('')

    else:
        comment_form = CommentForm()

    return render(request, 'mainapp/articles/article_{}.html'.format(pk), {'article': art, 'comment_form': comment_form,

mainapp/templates/mainapp/main.html
{% extends 'mainapp/basic_templates/base.html'%}
{% load staticfiles %}

{% block title %}
   <title>Мир Каратэ</title>
{% endblock %}

{% block content %}

    <div class="menu_articles">

        {% for type in types %}
            <a href="{% url 'articles:type' type.pk %}">
                <div class="item_menu_articles" {% if type.type_rus == 'Спортивные лагеря' %} style="display: none" {% endif %}>
                    {{ type.type_rus }}
                </div> 
            </a>
        {% endfor %}
        
        <a href="{% url 'articles:type' 'nonfiction' %}">
            <div class="item_menu_articles">
                Публицистика
            </div> 
        </a>

        <!-- <a href="{% url 'articles:type' 0 %}">
            <div class="item_menu_articles">
                Все статьи
            </div> 
        </a> -->

    </div>
    
    {% if countries %}
        <!--<div class="select_country">-->
            <div class="dropdown">
                <a class="select_country dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Выбрать страну
                </a>
                
                <!--a class="btn btn-secondary dropdown-toggle"-->

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    {% for country in countries %}
                        {% if country.name_rus == 'Россия' %}
                            <a class="dropdown-item dropdown-item_russia" href="{% url 'articles:country' 1 country.id %}">
                                {{ country.name_rus }}
                            </a>
                        {% else %}
                            <a class="dropdown-item" href="{% url 'articles:country' 1 country.id %}">
                                {{ country.name_rus }}
                            </a>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        <!--</div>-->
    {% endif %}

    <div class="menu_countries">

        {% for country in countries %}
            {% if country.name_rus == 'Россия' %}
                <a href="{% url 'articles:country' 1 country.id %}">
                    <div class="item_menu_countries_russia">
                        {{ country.name_rus }}
                    </div>
                </a>
            {% else %}
                <a href="{% url 'articles:country' 1 country.id %}">
                    <div class="item_menu_countries">
                        {{ country.name_rus }}
                    </div>
                </a>
            {% endif %}
        {% endfor %}

    </div>
    
    <div class="container_articles">
        
        {% if main_page_article %}
       
            <a {% if main_page_article.editor %} href="{{main_page_article.editor.get_absolute_url}}" {% elif main_page_article.nonfiction %} href="{{main_page_article.nonfiction.get_absolute_url}}" {% elif main_page_article.album %} href="{{main_page_article.album.get_absolute_url}}" {% elif main_page_article.video %} href="{{main_page_article.video.get_absolute_url}}" {%endif%} target="_blank" style="text-decoration: none">

                <div class="item_articles">

                    <img {% if main_page_article.editor %} src="{% static 'images/plume.jpg' %}" {% elif main_page_article.nonfiction %} src="{% static 'images/book.jpg' %}" {% elif main_page_article.album %} src="{{main_page_article.album.image1.url}}" {% elif main_page_article.video %} src="{% static 'images/video.jpg' %}" {%endif%}>

                    <div class="item_articles_title">
                        <div class="item_articles_title_inner"> {% if main_page_article.editor %} {{main_page_article.editor.title}} {% elif main_page_article.nonfiction %} {{main_page_article.nonfiction.title}}  {% elif main_page_article.album %} {{main_page_article.album.title_rus}} {% elif main_page_article.video %} {{main_page_article.video.title_rus}} {%endif%} </div>
                    </div>

                </div>

            </a>
                
        {% endif %}

        {% for item in article_item %}

            <a {% if show_editor %} href="{% url 'articles:editor_id' item.pk %}" {% elif show_nonfiction %} href="{% url 'articles:nonfiction' item.pk %}" {% else %} href="{% url 'articles:id' item.pk %}" {% endif %} target="_blank" style="text-decoration: none">

                    <div class="item_articles">

                        {% if item.image %}
                            <img src="{{ item.image.url }}">
                        {% elif show_editor %}
                            <img src="{% static 'images/plume.jpg' %}">
                        {% elif show_nonfiction %}
                            <img src="{% static 'images/book.jpg' %}">
                        {% else %}
                            <img src="{{ item.country.flag.url }}">
                        {% endif %}

                        <!--{% if item.flag %}<img src="{{ item.flag.url }}">{% endif %}-->

                        <div class="item_articles_title">
                            <div class="item_articles_title_inner">{{ item.title }}</div>
                        </div>

                    </div>
                    
            </a>

        {% endfor %}        

    </div>
    
    {% if number_of_articles > 100 %}
    
        <div style="text-align: center; margin-top: 10px;">
    
            {% if show_all %}
                <a href="{% url 'show_all'%}" target="_blank"><button type="button" class="btn btn-light">{{show_all}}</button></a>
            {% endif %}

            {% if show_competitions %}
                <a href="{% url 'show_competitions'%}" target="_blank"><button type="button" class="btn btn-light">{{show_competitions}}</button></a>
            {% endif %}

            {% if show_sport_camps %}
                <a href="{% url 'show_sport_camps'%}" target="_blank"><button type="button" class="btn btn-light">{{show_sport_camps}}</button></a>
            {% endif %}

            {% if show_sport_science %}
                <a href="{% url 'show_sport_science'%}" target="_blank"><button type="button" class="btn btn-light">{{show_sport_science}}</button></a>
            {% endif %}

            {% if show_editor %}
                <a href="{% url 'show_editor'%}" target="_blank"><button type="button" class="btn btn-light">{{show_editor}}</button></a>
            {% endif %}
            
            {% if show_nonfiction %}
                <a href="{% url 'show_nonfiction'%}" target="_blank"><button type="button" class="btn btn-light">{{show_nonfiction}}</button></a>
            {% endif %}
        
        </div>
    
    {% endif %}
    
{% endblock %}

mainapp/templates/mainapp/photo.html
{% extends 'mainapp/basic_templates/base_gallery.html'%}
{% load staticfiles %}

{% block title %}
   <title>Мир каратэ: Фотоальбомы</title>
{% endblock %}

{% block content %}
   
   
   
   <div class="title_article_i gallery_title" style="margin-bottom: 10px;">Фотоальбомы</div>
    
        <div class="container card-columns">
            
            {% for item in gallery_item %}
               <a href="{% url 'articles:photo_id' item.pk %}"><div class="card text-white">{%if item.image1%}<img class="card-img" src="{{item.image1.url}}" alt="Card image">{%endif%}
                <div class="card-img-overlay d-flex flex-column justify-content-between">
                    <div class="top_block text-right">
                        {{item.date}}
                    </div>
                    <div class="bottom_block">
                        {{item.title_rus}}
                    </div>
                </div>
                </div></a> 
            {% endfor %}

       </div>
       
    {% if number_of_albums > 30 %}
    
        <div style="text-align: center; margin-top: 10px;">
    
            <a href="{% url 'show_photo'%}" target="_blank"><button type="button" class="btn btn-dark">Показать остальные фотоальбомы</button></a>
        
        </div>
    
    {% endif %}
    
{% endblock %}

mainapp/templates/mainapp/search.html
{% extends 'mainapp/basic_templates/base_no_logo.html'%}

{% load staticfiles %}

{% block title %}
   <title>Мир каратэ: результаты поиска</title>
{% endblock %}

{% block menu_main_page %}
    <a href="{% url 'articles:main' %}"><div class="menu_main_page">На главную</div></a>
{% endblock %}

          
{% block content %}
    <div>  
    <h3>Результаты поиска: {{ found_articles.count|add:found_editors.count|add:found_nonfiction.count|add:found_albums.count|add:found_videos.count }}</h3>
    
    {% if found_articles %}<h5 align="center" style="margin-top: 10px; color: #b3051c;">Статьи на главной</h5>{% endif %}
    
    <div class="search_container">
        {% for article in found_articles %}
            <a class="search_title_text" href="{{ article.get_absolute_url }}" target="_blank">

                <div class="search_date">
                    {{ article.date }}
                </div>
                <div class="search_title">
                    {{ article.title }}
                </div>
                <!--<div class="search_text">
                    <i>{{ article.text|truncatewords:15 }}</i>
                </div>-->

            </a>
        {% endfor %}
    </div>
    
    {% if found_editors %}<h5 align="center" style="margin-top: 10px; color: #b3051c;">Статьи главного редактора</h5>{% endif %}
    
    <div class="search_container">
        {% for editor in found_editors %}
            <a class="search_title_text" href="{{ editor.get_absolute_url }}" target="_blank">

                <div class="search_date">
                    {{ editor.date }}
                </div>
                <div class="search_title">
                    {{ editor.title }}
                </div>

            </a>
        {% endfor %}
    </div>
    
    {% if found_nonfiction %}<h5 align="center" style="margin-top: 10px; color: #b3051c;">Публицистика</h5>{% endif %}
    
    <div class="search_container">
        {% for editor in found_nonfiction %}
            <a class="search_title_text" href="{{ editor.get_absolute_url }}" target="_blank">

                <div class="search_date">
                    {{ editor.date }}
                </div>
                <div class="search_title">
                    {{ editor.title }}
                </div>

            </a>
        {% endfor %}
    </div>
    
    {% if found_albums %}<h5 align="center" style="margin-top: 10px; color: #b3051c;">Фотоальбомы</h5>{% endif %}
    
    <div class="search_container">
        {% for album in found_albums %}
            <a class="search_title_text" href="{{ album.get_absolute_url }}" target="_blank">

                <div class="search_date">
                    {{ album.date }}
                </div>
                <div class="search_title">
                    {{ album.title_rus }}
                </div>

            </a>
        {% endfor %}
    </div>
    
    {% if found_videos %}<h5 align="center" style="margin-top: 10px; color: #b3051c;">Видео</h5>{% endif %}
    
    <div class="search_container">
        {% for video in found_videos %}
            <a class="search_title_text" href="{{ video.get_absolute_url }}" target="_blank">

                <div class="search_date">
                    {{ video.date }}
                </div>
                <div class="search_title">
                    {{ video.title_rus }}
                </div>

            </a>
        {% endfor %}
    </div>
    
    </div>

{% endblock %}

mainapp/templates/mainapp/show_all.html
{% extends 'mainapp/basic_templates/base_no_logo.html'%}

{% load staticfiles %}

{% block title %}
   <title>Мир каратэ: все статьи</title>
{% endblock %}
          
{% block content %}
   
    <div>
         
        <h3>Все статьи: {{ articles.count }}</h3>

        <div class="search_container">
            {% for article in articles %}
                <a class="search_title_text" href="{{ article.get_absolute_url }}" target="_blank">

                    <div class="search_date">
                        {{ article.date }}
                    </div>
                    <div class="search_title">
                        {{ article.title }}
                    </div>
                    
                </a>
            {% endfor %}
        </div>
    
    </div>

{% endblock %}

mainapp/templates/mainapp/show_competitions.html
{% extends 'mainapp/basic_templates/base_no_logo.html'%}

{% load staticfiles %}

{% block title %}
   <title>Мир каратэ: соревнования</title>
{% endblock %}
          
{% block content %}
    <div> 
        
        <h3>Соревнования: {{ articles.count }}</h3>

        <div class="search_container">
            {% for article in articles %}
                <a class="search_title_text" href="{{ article.get_absolute_url }}" target="_blank">

                    <div class="search_date">
                        {{ article.date }}
                    </div>
                    <div class="search_title">
                        {{ article.title }}
                    </div>

                </a>
            {% endfor %}
        </div>
    
    </div>

{% endblock %}

mainapp/templates/mainapp/show_editor.html
{% extends 'mainapp/basic_templates/base_no_logo.html'%}

{% load staticfiles %}

{% block title %}
   <title>Мир каратэ: Статьи главного редактора</title>
{% endblock %}
          
{% block content %}
   
    <div>
         
        <h3>Статьи главного редактора: {{ articles.count }}</h3>

        <div class="search_container">
            {% for article in articles %}
                <a class="search_title_text" href="{{ article.get_absolute_url }}" target="_blank">

                    <div class="search_date">
                        {{ article.date }}
                    </div>
                    <div class="search_title">
                        {{ article.title }}
                    </div>
                    
                </a>
            {% endfor %}
        </div>
    
    </div>

{% endblock %}

mainapp/templates/mainapp/show_nonfiction.html
{% extends 'mainapp/basic_templates/base_no_logo.html'%}

{% load staticfiles %}

{% block title %}
   <title>Мир каратэ: Публицистика</title>
{% endblock %}
          
{% block content %}
   
    <div>
         
        <h3>Публицистика: {{ articles.count }}</h3>

        <div class="search_container">
            {% for article in articles %}
                <a class="search_title_text" href="{{ article.get_absolute_url }}" target="_blank">

                    <div class="search_date">
                        {{ article.date }}
                    </div>
                    <div class="search_title">
                        {{ article.title }}
                    </div>
                    
                </a>
            {% endfor %}
        </div>
    
    </div>

{% endblock %}

mainapp/templates/mainapp/show_photo.html
{% extends 'mainapp/basic_templates/base_no_logo.html'%}

{% load staticfiles %}

{% block title %}
   <title>Мир каратэ: Фотоальбомы</title>
{% endblock %}
          
{% block content %}
   
    <div>
         
        <h3>Фотоальбомы: {{ photo.count }}</h3>

        <div class="search_container">
            {% for photo in photo %}
                <a class="search_title_text" href="{{ photo.get_absolute_url }}" target="_blank">

                    <div class="search_date">
                        {{ photo.date }}
                    </div>
                    <div class="search_title">
                        {{ photo.title_rus }}
                    </div>
                    
                </a>
            {% endfor %}
        </div>
    
    </div>

{% endblock %}

mainapp/templates/mainapp/video.html
{% extends 'mainapp/basic_templates/base_gallery.html'%}
{% load staticfiles %}

{% block title %}
   <title>Мир каратэ: Видео</title>
{% endblock %}

{% block content %}
   
   
   
    <div class="title_article_i gallery_title" style="margin-bottom: 10px;">Видео</div>
    
    <div class="container d-flex flex-row justify-content-center flex-wrap">
        
        {% for item in video_item %}
        
            <a href="{% url 'articles:video_id' item.pk%}" class="video_item_link"><div class="card text-white mb-3 video_item" style="max-width: 18rem;">
                <div class="card-body">
                <h5 class="card-title text-center">{{item.title_rus}}</h5>
                </div>
            </div></a>
            
        {% endfor %}
    
    </div>
    
    {% if number_of_videos > 30 %}
    
        <div style="text-align: center; margin-top: 10px;">
    
            <a href="{% url 'show_video'%}" target="_blank"><button type="button" class="btn btn-dark">Показать остальные видео</button></a>
        
        </div>
    
    {% endif %}
    
{% endblock %}