authapp/urls.py
import authapp.views as authapp
from django.urls import path

app_name = 'authapp'

urlpatterns = [
    path('login/ru', authapp.login, name='login'),
    path('logout/ru', authapp.logout, name='logout'),
    path('register/ru', authapp.register, name='register'),
    path('edit/ru', authapp.edit, name='edit'),
    path('login/', authapp.login_eng, name='login_eng'),
    path('logout/', authapp.logout_eng, name='logout_eng'),
    path('register/', authapp.register_eng, name='register_eng'),
    path('edit/', authapp.edit_eng, name='edit_eng'),
]

karateworld/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp.views import SearchView, shotokan, shito, goju, wado, \
    show_all_view, show_competitions_view, show_sport_camps_view, show_sport_science_view, show_editor_view, \
    show_nonfiction_view, show_photo_view, show_video_view

from mainapp_english.views import SearchViewEng, shotokan_eng, shito_eng, goju_eng, wado_eng, \
    show_all_view_eng, show_competitions_view_eng, show_sport_camps_view_eng, show_sport_science_view_eng, \
    show_editor_view_eng, show_photo_view_eng, show_video_view_eng

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('search/', SearchViewEng.as_view(), name = 'search_eng'),
    path('shotokan/', shotokan_eng, name='shotokan_eng'),
    path('shito-ryu/', shito_eng, name='shito_eng'),
    path('goju-ryu/', goju_eng, name='goju_eng'),
    path('wado-ryu/', wado_eng, name='wado_eng'),
    path('all_articles/', show_all_view_eng, name='show_all_eng'),
    path('competitions/', show_competitions_view_eng, name='show_competitions_eng'),
    path('sport_camps/', show_sport_camps_view_eng, name='show_sport_camps_eng'),
    path('sport_science/', show_sport_science_view_eng, name='show_sport_science_eng'),
    path('editor_in_chief/', show_editor_view_eng, name='show_editor_eng'),
    path('photo_albums/', show_photo_view_eng, name='show_photo_eng'),
    path('videos/', show_video_view_eng, name='show_video_eng'),
    #path('editor_articles/', show_editor_view_eng, name='show_editors_eng'),

    path('ru/search/', SearchView.as_view(), name = 'search'),
    path('ru/shotokan/', shotokan, name='shotokan'),
    path('ru/shito-ryu/', shito, name='shito'),
    path('ru/goju-ryu/', goju, name='goju'),
    path('ru/wado-ryu/', wado, name='wado'),
    path('ru/all_articles/', show_all_view, name='show_all'),
    path('ru/competitions/', show_competitions_view, name='show_competitions'),
    path('ru/sport_camps/', show_sport_camps_view, name='show_sport_camps'),
    path('ru/sport_science/', show_sport_science_view, name='show_sport_science'),
    path('ru/editor_in_chief/', show_editor_view, name='show_editor'),
    path('ru/nonfiction/other/', show_nonfiction_view, name='show_nonfiction'),
    path('ru/photo_albums/', show_photo_view, name='show_photo'),
    path('ru/videos/', show_video_view, name='show_video'),
    #path('ru/editor_articles/', show_editor_view, name='show_editors'),
    path('ru/', include('mainapp.urls', namespace = 'articles')),
    path('', include('mainapp_english.urls', namespace = 'main')),

    path('auth/', include('authapp.urls', namespace = 'auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mainapp/urls.py
import mainapp.views as mainapp
from django.urls import path

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.articles, name='main'),
    path('photo/', mainapp.gallery_photo, name='photo'),
    path('video/', mainapp.gallery_video, name='video'),
    #path('editor_in_chief/', mainapp.editor_in_chief, name='editor_in_chief'),
    path('photo/<pk>/', mainapp.photo_album, name='photo_id'),
    path('video/<pk>/', mainapp.video_album, name='video_id'),
    path('editor_in_chief/<pk>/', mainapp.editor_article, name='editor_id'),
    path('nonfiction/<pk>/', mainapp.nonfiction_article, name='nonfiction'),
    path('<pk>/', mainapp.articles, name='type'),
    path('<pk>/country/<id>/', mainapp.articles, name='country'),
    path('article/<pk>/', mainapp.article, name='id'),
]

mainapp/views.py
#coding=utf-8
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models import ArticleCategory, Country, Article, PhotoAlbum, Video, EditorArticle, Nonfiction, MainPageArticle
from commentapp.forms import CommentForm
from commentapp.models import Comment
from django.db.models import Q
from django.views import View


def articles(request, pk=None, id=None):

    article_item_all = Article.objects.all().order_by('-id')
    number_of_articles = len(article_item_all)
    article_item = article_item_all[:101]
    types = ArticleCategory.objects.all()
    countries = []
    show_all = ''
    show_competitions = ''
    show_sport_camps = ''
    show_sport_science = ''
    show_editor = ''
    show_nonfiction = ''
    article_type = {}

    if pk:

        if pk == '0':
            article_type = {'type_rus': 'все', 'pk':0}
            article_item = Article.objects.all().order_by('-id')[:101]
            show_all = 'Показать остальные статьи'

        elif pk == '1':
            article_item = Article.objects.filter(type__id=pk).order_by('-date_start')[:101]
            article_type = get_object_or_404(ArticleCategory, pk=pk)
            countries = Country.objects.all().order_by('name_rus')
            show_competitions = 'Показать остальные соревнования'
            if id:
                article_item = Article.objects.filter(country__id=id).order_by('-date_start')[:31]
                return render(request, 'mainapp/main.html',
                              {'article_item': article_item, 'article_type': article_type, 'types': types,
                               'countries': countries})

        elif pk == '2':
            article_item = Article.objects.filter(type__id=pk).order_by('-date_start')[:51]
            article_type = get_object_or_404(ArticleCategory, pk=pk)
            show_sport_camps = 'Показать остальные лагеря'

        elif pk == '3':
            article_item = Article.objects.filter(type__id=pk).order_by('-id')[:31]
            article_type = get_object_or_404(ArticleCategory, pk=pk)
            show_sport_science = 'Показать остальные статьи'

        elif pk == '4':
            #article_item = Article.objects.filter(type__id=pk).order_by('-id')[:31]
            article_item = EditorArticle.objects.all().order_by('-id')[:31]
            article_type = get_object_or_404(ArticleCategory, pk=pk)
            show_editor = 'Показать остальные статьи'

        elif pk == 'nonfiction':
            article_item = Nonfiction.objects.all().order_by('-id')[:31]
            #article_type = get_object_or_404(ArticleCategory, pk=pk)
            show_nonfiction = 'Показать остальные статьи'

        return render(request, 'mainapp/main.html', {'number_of_articles': number_of_articles,
                                                     'article_item': article_item, 'article_type': article_type,
                                                        'types': types, 'countries': countries, 'show_all': show_all,
                                                        'show_competitions': show_competitions,
                                                        'show_sport_camps': show_sport_camps,
                                                        'show_sport_science': show_sport_science,
                                                        'show_editor': show_editor, 'show_nonfiction': show_nonfiction})

    show_all = 'Показать остальные статьи'

    if len(MainPageArticle.objects.all()) > 0:
        main_page_article = MainPageArticle.objects.all().order_by('-id')[0]
    else:
        main_page_article = ''

    return render(request, 'mainapp/main.html', {'number_of_articles': number_of_articles, 'article_item': article_item,
                                                 'types': types, 'show_all': show_all,
                                                 'main_page_article': main_page_article})


def show_all_view(request):
    art = Article.objects.all().order_by('-id')[101:]
    return render(request, 'mainapp/show_all.html', {'articles': art})


def show_competitions_view(request):
    art = Article.objects.filter(type__id=1).order_by('-date_start')[101:]
    return render(request, 'mainapp/show_competitions.html', {'articles': art})


def show_sport_camps_view(request):
    art = Article.objects.filter(type__id=2).order_by('-date_start')[51:]
    return render(request, 'mainapp/show_sport_camps.html', {'articles': art})


def show_sport_science_view(request):
    art = Article.objects.filter(type__id=3).order_by('-id')[31:]
    return render(request, 'mainapp/show_sport_science.html', {'articles': art})


def show_editor_view(request):
    art = Article.objects.filter(type__id=4).order_by('-id')[31:]
    return render(request, 'mainapp/show_editor.html', {'articles': art})


def show_nonfiction_view(request):
    art = Nonfiction.objects.all().order_by('-id')[31:]
    return render(request, 'mainapp/show_nonfiction.html', {'articles': art})


def show_photo_view(request):
    photo = PhotoAlbum.objects.all().order_by('-id')[31:]
    return render(request, 'mainapp/show_photo.html', {'photo': photo})


def show_video_view(request):
    video = Video.objects.all().order_by('-id')[31:]
    return render(request, 'mainapp/show_video.html', {'video': video})


# def show_editor_view(request):
#     editors = EditorArticle.objects.all().order_by('-id')[31:]
#     return render(request, 'mainapp/show_editors.html', {'editors': editors})


def shotokan(request):
    return render(request, 'mainapp/styles/shotokan.html')


def shito(request):
    return render(request, 'mainapp/styles/shito.html')


def goju(request):
    return render(request, 'mainapp/styles/goju.html')


def wado(request):
    return render(request, 'mainapp/styles/wado.html')


def gallery_photo(request):

    number_of_albums = len(PhotoAlbum.objects.all().order_by('-id'))
    gallery_item = PhotoAlbum.objects.all().order_by('-id')[:31]

    return render(request, 'mainapp/photo.html', {'number_of_albums': number_of_albums, 'gallery_item': gallery_item})


def gallery_video(request):

    number_of_videos = len(Video.objects.all().order_by('-id'))
    video_item = Video.objects.all().order_by('-id')[:31]

    return render(request, 'mainapp/video.html', {'number_of_videos':number_of_videos, 'video_item': video_item})


# def editor_in_chief(request):
#
#     number_of_editors = len(EditorArticle.objects.all().order_by('-id'))
#     editor_item = EditorArticle.objects.all().order_by('-id')[:31]
#
#     return render(request, 'mainapp/editor_in_chief.html', {'number_of_editors': number_of_editors,
#                                                             'editor_item': editor_item})


class SearchView(View):

    template_name = 'mainapp/search.html'

    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('q')
        found_articles = Article.objects.filter(Q(title__icontains=query)|Q(text__icontains=query)|
                                                Q(title__icontains=query.title())|
                                                Q(text__icontains=query.title())|Q(city_description__icontains=query)|
                                                 Q(city_description__icontains=query.title())).order_by('-id')
        found_albums = PhotoAlbum.objects.filter(Q(title_rus__icontains=query)|
                                                 Q(title_rus__icontains=query.title())).order_by('-id')
        found_videos = Video.objects.filter(Q(title_rus__icontains=query) |
                                                 Q(title_rus__icontains=query.title())|Q(description_rus__icontains=query)|
                                                 Q(description_rus__icontains=query.title())).order_by('-id')
        found_editors = EditorArticle.objects.filter(Q(title__icontains=query) |
                                            Q(title__icontains=query.title())|Q(text__icontains=query) |
                                            Q(text__icontains=query.title())).order_by('-id')
        found_nonfiction = Nonfiction.objects.filter(Q(title__icontains=query) |
                                                     Q(title__icontains=query.title()) | Q(text__icontains=query) |
                                                     Q(text__icontains=query.title())).order_by('-id')

        context = {'found_articles': found_articles, 'found_albums': found_albums,
                   'found_videos': found_videos, 'found_editors': found_editors, 'found_nonfiction': found_nonfiction}

        return render(self.request, self.template_name, context)

#def search(request):
#
#    query = request.GET.get('q')
#    found_articles = Article.objects.filter(Q(title__icontains=query)|Q(text__icontains=query))
#
#    context = {'found_articles': found_articles}
#
#    return render(request, 'mainapp/search.html', context)

# -------------------------article_i-----------------------------


def article(request, pk=None):

    art = get_object_or_404(Article, pk=pk)
    comment = Comment.objects.filter(article_id=art).order_by('id')

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            comm = comment_form.save(commit=False)
            comm.author_id = request.user
            comm.article_id = art
            if request.user.avatar:
                comm.avatar = request.user.avatar.url
            comm.save()
            return HttpResponseRedirect('')

    else:
        comment_form = CommentForm()

    return render(request, 'mainapp/articles/article_{}.html'.format(pk), {'article': art, 'comment_form': comment_form,

mainapp/templates/mainapp/articles/article_1.html
{% extends 'mainapp/basic_templates/base.html'%}

{% load staticfiles %}

{% block title %}
   <title>Мир Каратэ: {{article.title}}</title>
{% endblock %}
          
{% block content %}
      
    <div class="container_article_i">
        
        <div class="article_date">
            {{article.date}}
        </div>

        <div class="title_article_i">{{article.title}}</div>

        <div class="date_article_i">{% if article.date_start %}{{article.date_start}}{% endif %} {% if article.date_end %}&mdash; {{article.date_end}}{% endif %}</div>
        
        {% if article.image_poster_logo_upper %}
            <div class="image_upper_article_i">
                <div>
                    <img src="{{article.image_poster_logo_upper.url}}">
                </div>
            </div>
        {% endif %}

        <div class="flex_container_1">

            <div class="image_left_article_i"><div>{% if article.image_poster_logo %}<img align="center" src="{{article.image_poster_logo.url}}">{% endif %}</div></div>


            <div class="flex_text">

                <div {% if article.type.id != 2 and article.type.id != 4 %} class="text_article_i" {% else %} class="city_description_article_i" style="font-size: 20px" {% endif %} align="justify"><div>{{article.text|safe}}</div></div>

                <div class="files_article_i" >

                    {% if article.file1 %}
                        <a href="{{article.file1.url}}" target="_blank" style="text-decoration: none"><div class="files_item">{{article.file1_name}}</div></a>
                    {% endif %}

                    {% if article.file2 %}
                        <a href="{{article.file2.url}}" target="_blank" style="text-decoration: none"><div class="files_item">{{article.file2_name}}</div></a>
                    {% endif %}
                    
                    {% if article.file3 %}
                        <a href="{{article.file3.url}}" target="_blank" style="text-decoration: none"><div class="files_item">{{article.file3_name}}</div></a>
                    {% endif %}
                    
                    {% if article.file4 %}
                        <a href="{{article.file4.url}}" target="_blank" style="text-decoration: none"><div class="files_item">{{article.file4_name}}</div></a>
                    {% endif %}
                    
                    {% if article.file5 %}
                        <a href="{{article.file5.url}}" target="_blank" style="text-decoration: none"><div class="files_item">{{article.file5_name}}</div></a>
                    {% endif %}

                </div>

                <div class="other_images_article_i">


                    {% if article.image1 %}
                        <div>
                            <img src="{{ article.image1.url }}">
                        </div>
                    {% endif %}

                    {% if article.image2 %}
                        <div>
                            <img src="{{ article.image2.url }}">
                        </div>
                    {% endif %}

                    {% if article.image3 %}
                        <div>
                            <img src="{{ article.image3.url }}">
                        </div>
                    {% endif %}

                    {% if article.image4 %}
                        <div>
                            <img src="{{ article.image4.url }}">
                        </div>
                    {% endif %}

                    {% if article.image5 %}
                        <div>
                            <img src="{{ article.image5.url }}">
                        </div>
                    {% endif %}

                    {% if article.image6 %}
                        <div>
                            <img src="{{ article.image6.url }}">
                        </div>
                    {% endif %}

                </div>

                <div class="city_description_article_i" align="justify">{{article.city_description|safe}}</div>

            </div>

        </div>


        <div class="city_photo_article_i">
            <div>
                {% if article.image_city_1 %}<img src="{{article.image_city_1.url}}">{% endif %}
            </div>
            <div>
                {% if article.image_city_2 %}<img src="{{article.image_city_2.url}}">{% endif %}
            </div>
        </div>
        
        <div class="additional_text">
            {% if article.additional_text %}{{article.additional_text|safe}}{% endif %}
        </div>

    </div>
          
    <hr> 

    <div class="comment_block">
        
        <h3>Комментарии {% if comment %} &bull; {{ comment|length }}  {% endif %}</h3>

        {% if user.is_authenticated %}
            <div class="comment_form">
               <form action="" method="post">
                  {% csrf_token %}
                  
                  {% for field in comment_form %}
                      <!--<div class="comment_field">-->
                          {{field}}
                      <!--</div>-->
                  {% endfor %}

                <div class="comment_buttons">
                                        
                  <input type="submit" value="Отправить">
                  <input type="reset" value="Очистить">
                
                </div>

               </form>
            </div>
        {% else %}
            <p class="auth_notification">Чтобы оставить комментарий, пожалуйста, <a href="{% url 'auth:login' %}">авторизуйтесь</a> или <a href="{% url 'auth:register' %}">зарегистрируйтесь</a>.</p>
        {% endif %}
        
        <div class="comments">
            {% for comm in comment %}
                <div class="comment_item">
                    
                    <div class="comment_avatar">
                        {% if comm.avatar %}<img src="{{ comm.avatar }}">{% else %}<img src="/static/images/anonimus.png"/>{% endif %}
                    </div>
                    
                    <div class="author_date_comment">
                        
                        <div class="author_date">
                            <div class="comment_author">
                                {{comm.author_id}}
                            </div>
                            <div class="comment_date">
                                {{comm.date}}
                            </div>
                        </div>
                        
                        <div class="comment_comment">
                            {{comm.comment}}
                        </div>
                         
                    </div>
                    
                </div>
            {% endfor %}
        </div>

    </div>

{% endblock %}